PACKAGE_NAME="#MODULE_NAME#"
PACKAGE_VERSION="#MODULE_VERSION#"

MAKE[0]="make KDIR=/lib/modules/${kernelver}/build all"
CLEAN="make KDIR=/lib/modules/${kernelver}/build clean"

BUILT_MODULE_NAME[0]="atomisp"
BUILT_MODULE_LOCATION[0]="drivers/staging/media/atomisp"
DEST_MODULE_LOCATION[0]="/kernel/drivers/staging/media/atomisp"

BUILT_MODULE_NAME[1]="atomisp_gmin_platform"
BUILT_MODULE_LOCATION[1]="drivers/staging/media/atomisp/pci"
DEST_MODULE_LOCATION[1]="/kernel/drivers/staging/media/atomisp/pci"

BUILT_MODULE_NAME[2]="ipu-bridge"
BUILT_MODULE_LOCATION[2]="external/ipu-bridge"
DEST_MODULE_LOCATION[2]="/kernel/drivers/media/pci/intel"

BUILT_MODULE_NAME[3]="mt9m114"
BUILT_MODULE_LOCATION[3]="external/mt9m114"
DEST_MODULE_LOCATION[3]="/kernel/drivers/media/i2c"

BUILT_MODULE_NAME[4]="ov9728"
BUILT_MODULE_LOCATION[4]="external/ov9728"
DEST_MODULE_LOCATION[4]="/kernel/drivers/media/i2c"

AUTOINSTALL="yes"
